import { NoteValueInfo, IntervalInfo, ScaleDefinition, ChordDefinition, ClefType } from './types';

export const NOTE_VALUES: NoteValueInfo[] = [
  {
    id: 'breve',
    beats: 8,
    fraction: '2/1',
    name: {
      tr: 'Breve (Çift Birlik)',
      en: 'Double Whole Note (Breve)',
      de: 'Doppelganze Note (Brevis)',
      ru: 'Бревис (Двойная целая)',
      ja: '二全音符 (ブリーヴ)',
      ar: 'نغمة مزدوجة كاملة (بريف)',
      fa: 'نت دو برابر گرد (برِو)',
    },
    restName: {
      tr: 'Çift Birlik Es (8 vuruş)',
      en: 'Double Whole Rest',
      de: 'Doppelganze Pause',
      ru: 'Пауза двойная целая',
      ja: '二全休符',
      ar: 'سكتة مضاعفة كاملة',
      fa: 'سکوت دو برابر گرد',
    },
    description: {
      tr: '4/4lük ölçüde 2 tam ölçü (8 vuruş) süren antik ve koral değer.',
      en: 'Equivalent to two whole notes or 8 quarter beats.',
      de: 'Dauert 8 Viertelschläge (zwei 4/4 Takte).',
      ru: 'Длительность равна 8 четвертным долям.',
      ja: '4/4拍子で2小節分（8拍）に相当する長い音符。',
      ar: 'تساوي مدة 8 نقرات في ميزان 4/4.',
      fa: 'برابر با هشت ضرب در میزان چهار چهارم.',
    },
  },
  {
    id: 'semibreve',
    beats: 4,
    fraction: '1/1',
    name: {
      tr: 'Birlik Nota (Semibreve)',
      en: 'Whole Note (Semibreve)',
      de: 'Ganze Note',
      ru: 'Целая нота',
      ja: '全音符',
      ar: 'نغمة كاملة (سيميبريف)',
      fa: 'نت گرد (کامل)',
    },
    restName: {
      tr: 'Birlik Es (4 vuruş)',
      en: 'Whole Rest',
      de: 'Ganze Pause',
      ru: 'Целая пауза',
      ja: '全休符',
      ar: 'سكتة كاملة',
      fa: 'سکوت گرد',
    },
    description: {
      tr: '4 vuruşluk temel süre birimi; içi boş yuvarlak kafa, sapsız.',
      en: 'Base unit of musical time in common time, 4 beats.',
      de: 'Dauert 4 Schläge, bildet den gesamten 4/4-Takt.',
      ru: 'Базовая длительность в 4 четверти (целый такт).',
      ja: '4/4拍子の1小節全体を満たす4拍の音符。',
      ar: 'تستغرق 4 نقرات كاملة في الميزان البسيط.',
      fa: 'دارای ارزش زمانی چهار ضرب کامل.',
    },
  },
  {
    id: 'minim',
    beats: 2,
    fraction: '1/2',
    name: {
      tr: 'İkilik Nota (Minim)',
      en: 'Half Note (Minim)',
      de: 'Halbe Note',
      ru: 'Половинная нота',
      ja: '二分音符',
      ar: 'نصف نغمة (مينيم)',
      fa: 'نت سفید',
    },
    restName: {
      tr: 'İkilik Es (2 vuruş)',
      en: 'Half Rest',
      de: 'Halbe Pause',
      ru: 'Половинная пауза',
      ja: '二分休符',
      ar: 'نصف سكتة',
      fa: 'سکوت سفید',
    },
    description: {
      tr: '2 vuruş değerindedir. İçi boş yuvarlak kafa ve dikey sap.',
      en: 'Lasts for 2 beats, half the duration of a whole note.',
      de: 'Dauert 2 Schläge (die Hälfte einer ganzen Note).',
      ru: 'Длится 2 четверти.',
      ja: '2拍分の長さを持つ音符。',
      ar: 'تستغرق نقرتين.',
      fa: 'ارزش زمانی برابر با دو ضرب.',
    },
  },
  {
    id: 'crotchet',
    beats: 1,
    fraction: '1/4',
    name: {
      tr: 'Dörtlük Nota (Crotchet)',
      en: 'Quarter Note (Crotchet)',
      de: 'Viertelnote',
      ru: 'Четвертная нота',
      ja: '四分音符',
      ar: 'ربع نغمة (كروتشيت / نوار)',
      fa: 'نت سیاه',
    },
    restName: {
      tr: 'Dörtlük Es (1 vuruş)',
      en: 'Quarter Rest',
      de: 'Viertelpause',
      ru: 'Четвертная пауза',
      ja: '四分休符',
      ar: 'سكتة الربع',
      fa: 'سکوت سیاه',
    },
    description: {
      tr: '1 vuruş süren standart temel vuruş birimi (içi dolu kafa ve sap).',
      en: 'Standard pulse unit, lasts for 1 beat.',
      de: 'Der Standard-Grundschlag in den meisten Taktarten (1 Schlag).',
      ru: 'Основная ритмическая единица, длится 1 долю.',
      ja: '音楽の基本となる1拍の音符。',
      ar: 'وحدة النبض الأساسية بقيمة نقرة واحدة.',
      fa: 'واحد ضرب پایه با ارزش زمانی یک ضرب.',
    },
  },
  {
    id: 'quaver',
    beats: 0.5,
    fraction: '1/8',
    name: {
      tr: 'Sekizlik Nota (Quaver)',
      en: 'Eighth Note (Quaver)',
      de: 'Achtelnote',
      ru: 'Восьмая нота',
      ja: '八分音符',
      ar: 'ثمن نغمة (كوافر / كروش)',
      fa: 'نت چنگ',
    },
    restName: {
      tr: 'Sekizlik Es (1/2 vuruş)',
      en: 'Eighth Rest',
      de: 'Achtelpause',
      ru: 'Восьмая пауза',
      ja: '八分休符',
      ar: 'سكتة الثمن',
      fa: 'سکوت چنگ',
    },
    description: {
      tr: 'Yarım (0.5) vuruş sürer; tek çengelli sapa sahiptir.',
      en: 'Lasts for half a beat (0.5 beats), has 1 flag/beam.',
      de: 'Dauert einen halben Schlag mit einem Fähnchen.',
      ru: 'Длится полдоли (с одним флажком).',
      ja: '0.5拍（半拍）の音符。符尾に1本の旗。',
      ar: 'تستغرق نصف نقرة، ولها سن واحد.',
      fa: 'نیم ضرب ارزش زمانی، دارای یک پرچم.',
    },
  },
  {
    id: 'semiquaver',
    beats: 0.25,
    fraction: '1/16',
    name: {
      tr: 'Onaltılık Nota (Semiquaver)',
      en: '16th Note (Semiquaver)',
      de: 'Sechzehntelnote',
      ru: 'Шестнадцатая нота',
      ja: '十六分音符',
      ar: 'نغمة جزء من 16 (دوبل كروش)',
      fa: 'نت دولاچنگ',
    },
    restName: {
      tr: 'Onaltılık Es (1/4 vuruş)',
      en: '16th Rest',
      de: 'Sechzehntelpause',
      ru: 'Шестнадцатая пауза',
      ja: '十六分休符',
      ar: 'سكتة جزء من 16',
      fa: 'سکوت دولاچنگ',
    },
    description: {
      tr: 'Çeyrek (0.25) vuruş sürer; çift çengelli sapa sahiptir.',
      en: 'Quarter of a beat (0.25), features 2 flags/beams.',
      de: 'Dauert 1/4 Schlag, zwei Fähnchen/Balken.',
      ru: 'Четверть доли, имеет два флажка.',
      ja: '0.25拍（1拍の4分の1）の音符。2本の旗。',
      ar: 'تستغرق ربع نقرة، ولها سنان.',
      fa: 'یک چهارم ضرب، با دو پرچم.',
    },
  },
  {
    id: 'demisemiquaver',
    beats: 0.125,
    fraction: '1/32',
    name: {
      tr: 'Otuzikilik Nota (Demisemiquaver)',
      en: '32nd Note (Demisemiquaver)',
      de: 'Zweiunddreißigstelnote',
      ru: 'Тридцать вторая нота',
      ja: '三十二分音符',
      ar: 'نغمة جزء من 32 (تريبل كروش)',
      fa: 'نت سه‌لاچنگ',
    },
    restName: {
      tr: 'Otuzikilik Es (1/8 vuruş)',
      en: '32nd Rest',
      de: 'Zweiunddreißigstelpause',
      ru: 'Тридцать вторая пауза',
      ja: '三十二分休符',
      ar: 'سكتة جزء من 32',
      fa: 'سکوت سه‌لاچنگ',
    },
    description: {
      tr: '1/8 vuruş sürer; 3 çengelli sap.',
      en: 'Lasts for 1/8 of a beat, features 3 flags.',
      de: 'Dauert 1/8 Schlag mit 3 Fähnchen.',
      ru: '1/8 доли с тремя флажками.',
      ja: '0.125拍（1拍の8分の1）の音符。3本の旗。',
      ar: 'تستغرق ثمن نقرة، ولها ثلاثة أسنان.',
      fa: 'یک هشتم ضرب، با سه پرچم.',
    },
  },
  {
    id: 'hemidemisemiquaver',
    beats: 0.0625,
    fraction: '1/64',
    name: {
      tr: 'Altmışdörtlük Nota (Hemidemisemiquaver)',
      en: '64th Note (Hemidemisemiquaver)',
      de: 'Vierundsechzigstelnote',
      ru: 'Шестьдесят четвёртая нота',
      ja: '六十四分音符',
      ar: 'نغمة جزء من 64 (كوادربل كروش)',
      fa: 'نت چهارلاچنگ',
    },
    restName: {
      tr: 'Altmışdörtlük Es (1/16 vuruş)',
      en: '64th Rest',
      de: 'Vierundsechzigstelpause',
      ru: 'Шестьдесят четвёртая пауза',
      ja: '六十四分休符',
      ar: 'سكتة جزء من 64',
      fa: 'سکوت چهارلاچنگ',
    },
    description: {
      tr: '1/16 vuruş; virtüöz pasajlar ve hızlı süslemeler için 4 çengelli sap.',
      en: 'Lasts for 1/16 of a beat, features 4 flags for virtuosic florid passages.',
      de: 'Dauert 1/16 Schlag, mit 4 Fähnchen für virtuose Verzierungen.',
      ru: '1/16 доли, используется в виртуозных пассажах.',
      ja: '非常に高速な装飾音やパッセージに使用される音符（4本の旗）。',
      ar: 'تستخدم في الممرات العزفية السريعة والزخارف المعقدة.',
      fa: 'کاربرد در پاساژهای سرعتی و فیگورهای ویرتوزیک.',
    },
  },
];

export const TIME_SIGNATURES = [
  { id: '2/4', beats: 2, unit: 4, type: 'Simple Duple', count: '1 - 2', description: 'Mars ve iki zamanlı adımlar' },
  { id: '3/4', beats: 3, unit: 4, type: 'Simple Triple', count: '1 - 2 - 3', description: 'Vals ve üç zamanlı danslar' },
  { id: '4/4', beats: 4, unit: 4, type: 'Simple Quadruple (Common Time)', count: '1 - 2 - 3 - 4', description: 'Standart popüler ve klasik ölçü' },
  { id: '6/8', beats: 6, unit: 8, type: 'Compound Duple', count: '1-2-3, 4-5-6 (2 ana vuruş)', description: 'Barcarolle ve pastoral dalgalı ritim' },
  { id: '9/8', beats: 9, unit: 8, type: 'Compound Triple / Aksak', count: '1-2-3, 4-5-6, 7-8-9 veya 2+2+2+3 (Aksak)', description: 'Klasik bileşik veya Türk/Balkan Aksak 9/8' },
  { id: '12/8', beats: 12, unit: 8, type: 'Compound Quadruple', count: '4 ana üçleme vuruşu', description: 'Blues shuffle ve zengin lirik temalar' },
  { id: '5/8', beats: 5, unit: 8, type: 'Additive / Aksak (2+3 veya 3+2)', count: '1-2, 1-2-3 (Düm-Te-Ke)', description: 'Türk Sanat/Halk Müziği Türk Aksağı & Bartók ritimleri' },
  { id: '7/8', beats: 7, unit: 8, type: 'Additive / Aksak (2+2+3 veya 3+2+2)', count: '1-2, 1-2, 1-2-3 (Devr-i Hindi)', description: 'Karadeniz / Balkan / Klasik Türk usulleri' },
];

export const INTERVALS: IntervalInfo[] = [
  {
    id: 'P1',
    semitones: 0,
    shortName: 'P1',
    ratio: '1:1',
    cents: 0,
    name: {
      tr: 'Tam Birli (Unison)',
      en: 'Perfect Unison (P1)',
      de: 'Reine Prime',
      ru: 'Чистая прима',
      ja: '完全1度',
      ar: 'أولى تامة (يونيسون)',
      fa: 'یکم درست (هم‌صدا)',
    },
    description: {
      tr: 'Aynı perdedeki iki ses. Sıfır frekans farkı, mükemmel rezonans.',
      en: 'Identical pitch. 0 cents difference, complete acoustic blend.',
      de: 'Gleicher Ton, vollkommener Zusammenklang.',
      ru: 'Два звука одинаковой высоты.',
      ja: '同一の高さの音。',
      ar: 'نفس الطبقة الصوتية تماماً.',
      fa: 'دو صدای با فرکانس کاملاً یکسان.',
    },
  },
  {
    id: 'm2',
    semitones: 1,
    shortName: 'm2',
    ratio: '16:15',
    cents: 100,
    name: {
      tr: 'Küçük İkili (Yarım Ses)',
      en: 'Minor 2nd (Half Step)',
      de: 'Kleine Sekunde',
      ru: 'Малая секунда',
      ja: '短2度 (半音)',
      ar: 'ثانية صغيرة (نصف بعد)',
      fa: 'دوم کوچک (نیم‌پرده)',
    },
    description: {
      tr: 'Yoğun disonans, güçlü çekim (Örn: Jaws film teması, Mi-Fa).',
      en: 'High dissonance, leading-tone tension (e.g. Jaws theme, E to F).',
      de: 'Starke Dissonanz, Leittonwirkung.',
      ru: 'Острая диссонантная семантика.',
      ja: '鋭い不協和音。半音の緊張感。',
      ar: 'تنافر صوتي حاد وشد إيقاعي.',
      fa: 'فاصله‌ای بسیار ناخوشایند و با کشش بالا.',
    },
  },
  {
    id: 'M2',
    semitones: 2,
    shortName: 'M2',
    ratio: '9:8',
    cents: 200,
    name: {
      tr: 'Büyük İkili (Tam Ses)',
      en: 'Major 2nd (Whole Step)',
      de: 'Große Sekunde',
      ru: 'Большая секунда',
      ja: '長2度 (全音)',
      ar: 'ثانية كبيرة (بعد كامل)',
      fa: 'دوم بزرگ (یک پرده)',
    },
    description: {
      tr: 'Dizi basamağı adımı (Do-Re, Sol-La).',
      en: 'Stepwise diatonic progression (e.g. Do-Re).',
      de: 'Schrittweise Melodiebewegung.',
      ru: 'Обычный шаг мажорной гаммы.',
      ja: '全音階の基本的なステップ。',
      ar: 'خطوة لحنية كاملة.',
      fa: 'گام ملودیک طبیعی پیوسته.',
    },
  },
  {
    id: 'm3',
    semitones: 3,
    shortName: 'm3',
    ratio: '6:5',
    cents: 300,
    name: {
      tr: 'Küçük Üçlü',
      en: 'Minor 3rd',
      de: 'Kleine Terz',
      ru: 'Малая терция',
      ja: '短3度',
      ar: 'ثالثة صغيرة',
      fa: 'سوم کوچک',
    },
    description: {
      tr: 'Minör tınının ve hüznün çekirdeği (La-Do, Do-Mib).',
      en: 'Core sadness / character of minor triads (e.g. Greensleeves).',
      de: 'Charakteristische Moll-Klangfarbe.',
      ru: 'Основа минорного трезвучия.',
      ja: '短調（マイナー）の哀愁ある響きの核。',
      ar: 'جوهر التآلف الصغير الحزين.',
      fa: 'پایه و بنیان آکورد مینور.',
    },
  },
  {
    id: 'M3',
    semitones: 4,
    shortName: 'M3',
    ratio: '5:4',
    cents: 400,
    name: {
      tr: 'Büyük Üçlü',
      en: 'Major 3rd',
      de: 'Große Terz',
      ru: 'Большая терция',
      ja: '長3度',
      ar: 'ثالثة كبيرة',
      fa: 'سوم بزرگ',
    },
    description: {
      tr: 'Majör parlaklığın ve konsonansın temeli (Do-Mi, Fa-La).',
      en: 'Bright, cheerful foundation of major chords (e.g. Oh When the Saints).',
      de: 'Helle, strahlende Konsonanz.',
      ru: 'Светлая, устойчивая мажорная терция.',
      ja: '明るい長調の基礎となる和声音程。',
      ar: 'أساس التآلف الكبير المشرق.',
      fa: 'صدادهی شفاف، درخشان و بنیاد ماژور.',
    },
  },
  {
    id: 'P4',
    semitones: 5,
    shortName: 'P4',
    ratio: '4:3',
    cents: 500,
    name: {
      tr: 'Tam Dörtlü',
      en: 'Perfect 4th (P4)',
      de: 'Reine Quarte',
      ru: 'Чистая кварта',
      ja: '完全4度',
      ar: 'رابعة تامة',
      fa: 'چهارم درست',
    },
    description: {
      tr: 'Antik armoni temeli, asil ve açık tını (Örn: Düğün Marşı, Do-Fa).',
      en: 'Open, noble sound (e.g. Here Comes the Bride, C to F).',
      de: 'Offener, kraftvoller Klang.',
      ru: 'Благородное, открытое звучание.',
      ja: '力強く安定した音程。',
      ar: 'صوت نبيل ومفتوح.',
      fa: 'صدای استوار و محکم دراماتیک.',
    },
  },
  {
    id: 'TT',
    semitones: 6,
    shortName: 'TT (d5 / A4)',
    ratio: '45:32 / √2',
    cents: 600,
    name: {
      tr: 'Triton (Artmış 4lü / Eksik 5li - Diabolus in Musica)',
      en: 'Tritone (Diminished 5th / Augmented 4th)',
      de: 'Tritonus (Diabolus in Musica)',
      ru: 'Тритон (ув.4 / ум.5)',
      ja: '三全音 (トライトーン)',
      ar: 'ترايتون (الخامسة الناقصة)',
      fa: 'تریتون (شیطان در موسیقی)',
    },
    description: {
      tr: 'Oktavı tam ortadan bölen 3 tam seslik en gerilimli aralık (Do-Fa#). Dominant 7 akorunun çözünme motoru.',
      en: 'Symmetrical octave-split with extreme tension. Resolves inward to 3rd or outward to 6th.',
      de: 'Höchste tonale Spannung, treibende Kraft der Dominantauflösung.',
      ru: 'Крайняя степень ладового тяготения.',
      ja: 'オクターブを二等分する最も緊張感の高い不協和音。',
      ar: 'أقصى درجات التوتر الصوتي في الموسيقى الكلاسيكية.',
      fa: 'پرتنش‌ترین فاصله آکوستیک که نیاز مبرم به حل شدن دارد.',
    },
  },
  {
    id: 'P5',
    semitones: 7,
    shortName: 'P5',
    ratio: '3:2',
    cents: 700,
    name: {
      tr: 'Tam Beşli (Keman Açık Tel Aralığı)',
      en: 'Perfect 5th (P5)',
      de: 'Reine Quinte',
      ru: 'Чистая квинта',
      ja: '完全5度',
      ar: 'خامسة تامة',
      fa: 'پنجم درست',
    },
    description: {
      tr: 'Müzik fiziğindeki en saf konsonans (3:2 oranı). Keman telleri (Sol-Re-La-Mi) tam 5li aralıkla akort edilir.',
      en: 'Purest acoustic consonance (3:2 ratio). Standard violin open string tuning (G-D-A-E).',
      de: 'Reinste Konsonanz, Stimmung der Geigensaiten (G-D-A-E).',
      ru: 'Идеальное созвучие, интервал настройки струн скрипки.',
      ja: '音響学上最も純粋な協和音程（3:2比率）。ヴァイオリンの調弦基準。',
      ar: 'أنقى بعد صوتي فيزيائياً، وهو دوزان أوتار الكمان.',
      fa: 'خالص‌ترین رزونانس هارمونیک و کوک سیم‌های ویولن.',
    },
  },
  {
    id: 'm6',
    semitones: 8,
    shortName: 'm6',
    ratio: '8:5',
    cents: 800,
    name: {
      tr: 'Küçük Altılı',
      en: 'Minor 6th',
      de: 'Kleine Sexte',
      ru: 'Малая секста',
      ja: '短6度',
      ar: 'سادسة صغيرة',
      fa: 'ششم کوچک',
    },
    description: {
      tr: 'Romantik ve nostaljik tını (Büyük üçlünün çevrimi).',
      en: 'Emotional, longing romantic character (e.g. Love Story theme).',
      de: 'Sehnsuchtsvoller, romantischer Ausdruck.',
      ru: 'Выразительный лирический интервал.',
      ja: '情緒的でロマンティックな響き。',
      ar: 'بعد رومانسي مليء بالشجن.',
      fa: 'بیانگر حس نوستالژی و رمانتیسم عمیق.',
    },
  },
  {
    id: 'M6',
    semitones: 9,
    shortName: 'M6',
    ratio: '5:3',
    cents: 900,
    name: {
      tr: 'Büyük Altılı',
      en: 'Major 6th',
      de: 'Große Sexte',
      ru: 'Большая секста',
      ja: '長6度',
      ar: 'سادسة كبيرة',
      fa: 'ششم بزرگ',
    },
    description: {
      tr: 'Huzurlu ve pastoral tını (Örn: Chopin Noktürnleri, Do-La).',
      en: 'Sweet, pastoral harmony (e.g. NBC Chimes, Chopin Nocturnes).',
      de: 'Lieblicher, pastoraler Klang.',
      ru: 'Светлый, пасторальный интервал.',
      ja: '温かみのある心地よい響き。',
      ar: 'بعد هادئ ورعوي عذب.',
      fa: 'فاصله‌ای دلنشین و آرامش‌بخش.',
    },
  },
  {
    id: 'm7',
    semitones: 10,
    shortName: 'm7',
    ratio: '16:9 / 9:5',
    cents: 1000,
    name: {
      tr: 'Küçük Yedili (Dominant 7 Aralığı)',
      en: 'Minor 7th',
      de: 'Kleine Septime',
      ru: 'Малая септима',
      ja: '短7度',
      ar: 'سابعة صغيرة',
      fa: 'هفتم کوچک',
    },
    description: {
      tr: 'Blues ve caz armonisi omurgası; dominant 7 akorunun üst sesi (Sol-Fa).',
      en: 'Backbone of blues & dominant 7th chords (e.g. Somewhere from West Side Story).',
      de: 'Fundament von Dominantseptakkorden und Blues.',
      ru: 'Основа доминантсептаккорда и джазовой гармонии.',
      ja: 'ブルースやドミナント7thコードの根幹となる音程。',
      ar: 'أساس تآلفات البلوز والسابعة المسيطرة.',
      fa: 'ستون اصلی آکوردهای دو مینانت هفتم و موسیقی بلوز.',
    },
  },
  {
    id: 'M7',
    semitones: 11,
    shortName: 'M7',
    ratio: '15:8',
    cents: 1100,
    name: {
      tr: 'Büyük Yedili (Yeden Sesi)',
      en: 'Major 7th',
      de: 'Große Septime',
      ru: 'Большая септима',
      ja: '長7度',
      ar: 'سابعة كبيرة',
      fa: 'هفتم بزرگ',
    },
    description: {
      tr: 'Oktava en yakın keskin çekim; sofistike Maj7 akor rengi (Do-Si).',
      en: 'Aching proximity to octave; shimmering Maj7 jazz color (e.g. Take On Me).',
      de: 'Schwebende, samtige Jazz-Dissonanz.',
      ru: 'Острое тяготение в тонику (вводный тон).',
      ja: 'トニックへの強い引力を持つ洗練された音程（Maj7コード）。',
      ar: 'حساسية عالية وجاذبية قصوى نحو النغمة الأساسية.',
      fa: 'کشش شدید به سمت نت پایه اکتاو و رنگ مدرن جَز.',
    },
  },
  {
    id: 'P8',
    semitones: 12,
    shortName: 'P8',
    ratio: '2:1',
    cents: 1200,
    name: {
      tr: 'Tam Sekizli (Oktav)',
      en: 'Perfect Octave (P8)',
      de: 'Reine Oktave',
      ru: 'Чистая октава',
      ja: '完全8度 (オクターブ)',
      ar: 'ثامنة تامة (أوكتاف)',
      fa: 'هشتم درست (اکتاو)',
    },
    description: {
      tr: 'Frekansın tam 2 katı (2:1 oranı). Akustik özdeşlik hissi.',
      en: 'Exact doubling of frequency (2:1). Complete harmonic identity.',
      de: 'Verdopplung der Frequenz (2:1), vollkommene Verschmelzung.',
      ru: 'Удвоение частоты (2:1), тождество звуков.',
      ja: '周波数が正確に2倍（2:1）となる音程。',
      ar: 'مضاعفة تردد الصوت تماماً (2:1).',
      fa: 'دو برابر شدن دقیق فرکانس صوتی (۲:۱).',
    },
  },
];

export const SCALES: ScaleDefinition[] = [
  {
    id: 'major',
    name: {
      tr: 'Majör Dizi (İyoniyen Modu)',
      en: 'Major Scale (Ionian Mode)',
      de: 'Dur-Tonleiter (Ionisch)',
      ru: 'Мажорный лад (Ионийский)',
      ja: '長音階 (イオニアン)',
      ar: 'السلم الكبير (العجم / إيونيان)',
      fa: 'گام ماژور (ایونیان / عجم)',
    },
    type: 'major',
    intervals: [0, 2, 4, 5, 7, 9, 11, 12],
    description: {
      tr: 'Formül: 2 Tam 1 Yarım 3 Tam 1 Yarım (T-T-Y-T-T-T-Y). Batı müziğinin temel taşı.',
      en: 'Formula: W-W-H-W-W-W-H (Whole and Half steps). Foundation of Western tonal music.',
      de: 'Formel: G-G-H-G-G-G-H (Ganz- und Halbtonschritte).',
      ru: 'Формула: тон-тон-полутон-тон-тон-тон-полутон.',
      ja: '全-全-半-全-全-全-半の構造を持つ西洋音楽の基本スケール。',
      ar: 'صيغته: بعد-بعد-نصف-بعد-بعد-بعد-نصف.',
      fa: 'فرمول: پرده-پرده-نیم‌پرده-پرده-پرده-پرده-نیم‌پرده.',
    },
  },
  {
    id: 'natural_minor',
    name: {
      tr: 'Doğal Minör (Eoliyen Modu)',
      en: 'Natural Minor Scale (Aeolian)',
      de: 'Natürliches Moll (Äolisch)',
      ru: 'Натуральный минор (Эолийский)',
      ja: '自然的短音階 (エオリアン)',
      ar: 'السلم الصغير الطبيعي (النهوند)',
      fa: 'مینور طبیعی (ائولین / نهوند)',
    },
    type: 'minor',
    intervals: [0, 2, 3, 5, 7, 8, 10, 12],
    description: {
      tr: 'Formül: T-Y-T-T-Y-T-T (1-2-b3-4-5-b6-b7). Hüzünlü ve doğal melodi yapısı.',
      en: 'Formula: W-H-W-W-H-W-W. Characteristic dark, reflective minor mode.',
      de: 'Formel: G-H-G-G-H-G-G.',
      ru: 'Строение: тон-полутон-тон-тон-полутон-тон-тон.',
      ja: '短音階の基本形。第3、第6、第7音が半音低い。',
      ar: 'السلم الصغير القياسي ذو الطابع الحزين.',
      fa: 'دارای درجات سوم، ششم و هفتم بمل.',
    },
  },
  {
    id: 'harmonic_minor',
    name: {
      tr: 'Armonik Minör Dizi',
      en: 'Harmonic Minor Scale',
      de: 'Harmonisches Moll',
      ru: 'Гармонический минор',
      ja: '和声的短音階',
      ar: 'السلم الصغير الهارموني',
      fa: 'مینور هارمونیک',
    },
    type: 'minor',
    intervals: [0, 2, 3, 5, 7, 8, 11, 12],
    description: {
      tr: '7. derecesi yarım ses tizleştirilerek yeden (sensible) ses elde edilir. 6-7 arası 1.5 seslik (artmış 2li) egzotik aralık oluşur.',
      en: 'Raised 7th degree creates a strong leading-tone and an augmented 2nd interval between b6 and 7.',
      de: 'Erhöhte 7. Stufe (Leitton) erzeugt einen übermäßigen Sekundschritt (1,5 Töne).',
      ru: 'Повышенная VII ступень создает вводный тон и увеличенную секунду.',
      ja: '第7音を半音上げて導音を作った短音階。異国情緒ある響き。',
      ar: 'تُرفع الدرجة السابعة بنصف بعد لخلق جاذبية هارمونية قوية.',
      fa: 'دارای درجه هفتم دیز شده و فاصله یک و نیم پرده‌ای بین ۶ و ۷.',
    },
  },
  {
    id: 'melodic_minor',
    name: {
      tr: 'Melodik Minör Dizi (Klasik Jazz)',
      en: 'Melodic Minor Scale',
      de: 'Melodisches Moll',
      ru: 'Мелодический минор',
      ja: '旋律的短音階',
      ar: 'السلم الصغير اللحني',
      fa: 'مینور ملودیک',
    },
    type: 'minor',
    intervals: [0, 2, 3, 5, 7, 9, 11, 12],
    description: {
      tr: 'Çıkarken 6. ve 7. dereceler tizleşir (1-2-b3-4-5-6-7), klasik teoride inerken doğal minöre döner.',
      en: 'Ascending: raised 6th and 7th degrees. In jazz, used both ascending and descending.',
      de: 'Beim Aufsteigen erhöhte 6. und 7. Stufe; beim Absteigen natürliches Moll.',
      ru: 'При движении вверх повышаются VI и VII ступени.',
      ja: '上行時に第6音・第7音を半音上げ、下行時に自然短音階に戻る。',
      ar: 'تُرفع الدرجتان السادسة والسابعة صعوداً وتعودان هبوطاً.',
      fa: 'در حالت بالارونده درجات ۶ و ۷ بکار و در برگشت طبیعی می‌شوند.',
    },
  },
  {
    id: 'dorian',
    name: {
      tr: 'Doryen Modu (2. Mod)',
      en: 'Dorian Mode',
      de: 'Dorischer Modus',
      ru: 'Дорийский лад',
      ja: 'ドリア旋法',
      ar: 'المقام الدوري (Dorian)',
      fa: 'مُد دورین',
    },
    type: 'mode',
    intervals: [0, 2, 3, 5, 7, 9, 10, 12],
    description: {
      tr: 'Doğal minörün 6. derecesinin doğal (büyük) hali (1-2-b3-4-5-6-b7). Carlos Santana, Miles Davis "So What" tınısı.',
      en: 'Minor scale with a bright natural 6th. Iconic jazz/rock modal sound.',
      de: 'Moll-Skala mit großer Sexte (dorische Sexte).',
      ru: 'Минорный лад с высокой VI ступенью (дорийская секста).',
      ja: '第6音がメジャー（ナチュラル）なマイナースケール。So Whatなどで有名。',
      ar: 'سلم صغير يتميز بدرجة سادسة كبيرة مشرقة.',
      fa: 'گام مینور با درجه ششم بزرگ که رنگ صوتی جادویی دارد.',
    },
  },
  {
    id: 'phrygian_dominant',
    name: {
      tr: 'Frigyen Dominant / Hicaz Dizisi',
      en: 'Phrygian Dominant (Hijaz Scale)',
      de: 'Phrygisch Dominant / Hedschas',
      ru: 'Фригийский доминантный / Хиджаз',
      ja: 'フリジアン・ドミナント (ヒジャーズ)',
      ar: 'مقام الحجاز (Hijaz Maqam)',
      fa: 'مقام حجاز / همایون',
    },
    type: 'makam',
    intervals: [0, 1, 4, 5, 7, 8, 10, 12],
    description: {
      tr: 'Armonik minörün 5. modu (1-b2-3-4-5-b6-b7). Akdeniz, Flamenko ve Türk Müziği Hicaz makamının temperlenmiş batı karşılığı.',
      en: '5th mode of Harmonic Minor (1-b2-3-4-5-b6-b7). Iconic Flamenco and Middle Eastern Hijaz sound.',
      de: '5. Modus von Harmonisch Moll. Typisch für Flamenco und orientalische Musik.',
      ru: 'V ступень гармонического минора, основа восточной музыки и фламенко.',
      ja: 'ハーモニックマイナーの第5モード。フラメンコや中東の代表的響き。',
      ar: 'من أشهر المقامات الشرقية، يعطي إحساساً بالخشوع والشجن والتطريب.',
      fa: 'صدادهی اصیل شرقی، فلامنکو و از پرکاربردترین فواصل موسیقی.',
    },
  },
  {
    id: 'rast_makam',
    name: {
      tr: 'Rast Makamı (Klasik Türk Müziği)',
      en: 'Rast Maqam (Traditional 53-TET)',
      de: 'Rast Makam (Traditionell)',
      ru: 'Макам Раст',
      ja: 'マカーム・ラスト',
      ar: 'مقام الرست (أبو المقامات)',
      fa: 'مقام راست (پدر دستگاه‌ها)',
    },
    type: 'makam',
    intervals: [0, 2, 3.5, 5, 7, 9, 10.5, 12],
    microtonalOffsets: [0, 0, -35, 0, 0, 0, -35, 0], // Segah & Eviç koma perdeleri
    description: {
      tr: 'Makamların atası kabul edilir. 3. perde (Segah) ve 7. perde (Eviç) yaklaşık 1 koma bemollüdür (Segah koması). Neşeli, dingin ve asil karakterlidir.',
      en: 'Known as the "Father of Maqamat". Features neutral 3rd (Segah) and neutral 7th with microtonal comma intonation.',
      de: 'Der Urvater der Makam-Musik mit Mikrointervallen (Segah-Koma).',
      ru: 'Основа восточной ладовой системы с микрохроматикой.',
      ja: '「諸マカームの父」と呼ばれる。微小音程（セガー・コマ）を含む高貴な旋法。',
      ar: 'يُلقب بـ "أبو المقامات"، يبعث على البهجة والاستقرار والفخامة.',
      fa: 'یکی از کهن‌ترین و اصلی‌ترین مقامات شرقی با فواصل ریزپرده‌ای.',
    },
  },
];

export const CHORDS: ChordDefinition[] = [
  { id: 'maj', name: 'Major', fullName: { tr: 'Majör Üçlü', en: 'Major Triad', de: 'Dur-Dreiklang', ru: 'Мажорное трезвучие', ja: 'メジャートライアド', ar: 'تآلف كبير', fa: 'آکورد ماژور' }, intervals: [0, 4, 7], formula: '1 - 3 - 5', category: 'triad' },
  { id: 'min', name: 'Minor', fullName: { tr: 'Minör Üçlü', en: 'Minor Triad', de: 'Moll-Dreiklang', ru: 'Минорное трезвучие', ja: 'マイナートライアド', ar: 'تآلف صغير', fa: 'آکورد مینور' }, intervals: [0, 3, 7], formula: '1 - b3 - 5', category: 'triad' },
  { id: 'dim', name: 'Diminished', fullName: { tr: 'Eksilmiş Üçlü', en: 'Diminished Triad', de: 'Verminderter Dreiklang', ru: 'Уменьшенное трезвучие', ja: 'ディミニッシュ', ar: 'تآلف ناقص', fa: 'آکورد کاسته' }, intervals: [0, 3, 6], formula: '1 - b3 - b5', category: 'triad' },
  { id: 'aug', name: 'Augmented', fullName: { tr: 'Artmış Üçlü', en: 'Augmented Triad', de: 'Übermäßiger Dreiklang', ru: 'Увеличенное трезвучие', ja: 'オーグメント', ar: 'تآلف زائد', fa: 'آکورد افزوده' }, intervals: [0, 4, 8], formula: '1 - 3 - #5', category: 'triad' },
  { id: 'dom7', name: 'Dominant 7th', fullName: { tr: 'Dominant Yedili', en: 'Dominant 7th', de: 'Dominantseptakkord', ru: 'Доминантсептаккорд', ja: 'ドミナントセブンス', ar: 'السابعة المسيطرة', fa: 'دو مینانت هفتم' }, intervals: [0, 4, 7, 10], formula: '1 - 3 - 5 - b7', category: 'seventh' },
  { id: 'maj7', name: 'Major 7th', fullName: { tr: 'Büyük Yedili (Maj7)', en: 'Major 7th', de: 'Großer Septakkord', ru: 'Большой мажорный септаккорд', ja: 'メジャーセブンス', ar: 'السابعة الكبيرة', fa: 'ماژور هفتم' }, intervals: [0, 4, 7, 11], formula: '1 - 3 - 5 - 7', category: 'seventh' },
  { id: 'min7', name: 'Minor 7th', fullName: { tr: 'Küçük Yedili (m7)', en: 'Minor 7th', de: 'Moll-Septakkord', ru: 'Малый минорный септаккорд', ja: 'マイナーセブンス', ar: 'السابعة الصغيرة', fa: 'مینور هفتم' }, intervals: [0, 3, 7, 10], formula: '1 - b3 - 5 - b7', category: 'seventh' },
  { id: 'dim7', name: 'Diminished 7th', fullName: { tr: 'Tam Eksilmiş 7li', en: 'Fully Diminished 7th', de: 'Ganz verminderter Septakkord', ru: 'Уменьшенный септаккорд', ja: 'ディミニッシュセブンス', ar: 'السابعة الناقصة الكاملة', fa: 'کاسته کامل هفتم' }, intervals: [0, 3, 6, 9], formula: '1 - b3 - b5 - bb7', category: 'seventh' },
  { id: 'm7b5', name: 'Half-Diminished', fullName: { tr: 'Yarı Eksilmiş (m7b5)', en: 'Half-Diminished 7th', de: 'Halbverminderter Septakkord', ru: 'Полуменьшенный септаккорд', ja: 'ハーフディミニッシュ', ar: 'نصف ناقص', fa: 'نیمه‌کاسته' }, intervals: [0, 3, 6, 10], formula: '1 - b3 - b5 - b7', category: 'seventh' },
  { id: 'sus4', name: 'Suspended 4th', fullName: { tr: 'Gecikmeli Dörtlü (Sus4)', en: 'Suspended 4th', de: 'Sus4-Akkord', ru: 'Задержанный аккорд (sus4)', ja: 'サスフォー', ar: 'معلق بالرابعة', fa: 'آکورد ساسپندد ۴' }, intervals: [0, 5, 7], formula: '1 - 4 - 5', category: 'triad' },
];
